### ISSUE TITLE
Add BluetoothLeManager and BluetoothManager

### ISSUE THREAD

**Issue by dieter115** [wisemen-digital/AndroidCore#17]
As we are writing more and more apps that require Bluetooth functionality, it is better to write some standard Bluetooth(Le) Managers instead of always start writing them from scratch.

**Comment by ChristianoBolla-Appwise** [comment]
@SibertSchurmans What do you think, you want to take a look into this with me, as we both have written some sort of manager lately?

**Comment by SibertSchurmans** [comment]
> @SibertSchurmans What do you think, you want to take a look into this with me, as we both have written some sort of manager lately?

Yes! I'm curious on how our approaches differ and what the best implementation can be 😄 
Let me know when you want to check it out! ( Maybe with the rest of circle android on an evening? )
